import {
  Briefcase,
  Megaphone,
  Target,
  Wallet,
  CreditCard,
  Users,
  LayoutGrid,
  Film,
  Landmark,
  FileSearch,
  ClipboardCheck,
  Mail,
  Monitor,
  PenTool,
  Star,
  BellRing,
  Send,
  UserSearch,
  StickyNote,
  Share2,
  FilePieChart,
  Inbox,
  BarChart3,
  Calculator,
  Receipt,
  FileText,
  FileCheck2,
  ScrollText,
  Car,
  TrendingUp,
  CalendarClock,
  Palmtree,
  CalendarDays,
  Clock,
  Network,
  FileSignature,
  Gift,
  Calendar,
  BookOpen,
  FolderOpen,
  FileArchive,
  Bell,
  Search,
  Flower2,
  KeyRound,
  Settings, // Settings 추가
} from "lucide-react";

export const NAV_CATEGORIES = [
  {
    id: "management",
    label: "매니지먼트",
    icon: <Briefcase className="w-6 h-6" />,
    color: "bg-indigo-500",
    gradient: "from-indigo-600 to-violet-700",
  },
  {
    id: "pr",
    label: "홍보",
    icon: <Megaphone className="w-6 h-6" />,
    color: "bg-blue-500",
    gradient: "from-blue-500 to-cyan-600",
  },
  {
    id: "marketing",
    label: "마케팅",
    icon: <Target className="w-6 h-6" />,
    color: "bg-rose-500",
    gradient: "from-rose-500 to-orange-600",
  },
  {
    id: "finance",
    label: "재무",
    icon: <Wallet className="w-6 h-6" />,
    color: "bg-emerald-500",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "hr",
    label: "인사",
    icon: <Users className="w-6 h-6" />,
    color: "bg-amber-500",
    gradient: "from-amber-500 to-orange-500",
  },
  {
    id: "common",
    label: "공용",
    icon: <LayoutGrid className="w-6 h-6" />,
    color: "bg-slate-500",
    gradient: "from-slate-500 to-slate-700",
  },
];

export const SUB_MENUS: Record<string, any[]> = {
  management: [
    { id: "scenario", name: "시나리오 분석", icon: <Film /> },
    { id: "internal-mail", name: "사내 메일/커뮤니케이션", icon: <Mail />, path: "/admin/mail" },
    { id: "contract-analysis", name: "계약서 분석", icon: <FileSearch /> },
    { id: "site-review", name: "현장 검토 사항", icon: <ClipboardCheck /> },
    { id: "select-monitor", name: "작품 셀렉 모니터링", icon: <Monitor /> },
  ],
  pr: [
    { id: "press-release", name: "원고생성", icon: <PenTool /> },
    { id: "profile-create", name: "프로필 제작", icon: <Star />, path: "/profiles" },
    { id: "news-monitor", name: "키워드 알림", icon: <BellRing /> },
    { id: "media-sending", name: "언론 보도 발송", icon: <Send />, path: "/admin/media-pitching" },
    { id: "profile-mgmt", name: "인물정보 관리", icon: <UserSearch />, path: "/profiles" },
    { id: "media-memo", name: "미디어 관계 메모", icon: <StickyNote /> },
    { id: "sns-posting", name: "SNS포스팅 생성", icon: <Share2 /> },
  ],
  marketing: [
    { id: "marketing-plan", name: "마케팅 전략", icon: <Target /> },
    { id: "performance", name: "성과보고서", icon: <FilePieChart /> },
    { id: "campaign", name: "캠페인 관리", icon: <Megaphone /> },
    { id: "brand-review", name: "브랜드 제안 검토함", icon: <Inbox /> },
    { id: "sns-dashboard", name: "SNS/노출 지표", icon: <BarChart3 /> },
    { id: "roi-sim", name: "ROI 시뮬레이션", icon: <Calculator /> },
  ],
  finance: [
    { id: "bank-transactions", name: "거래내역조회 (통장)", icon: <Landmark />, path: "/apps/finance/transactions" },
    { id: "card-history", name: "법인카드 사용내역", icon: <CreditCard />, path: "/apps/finance/card-history" },
    { id: "billing-inbox", name: "외부청구함", icon: <Receipt />, path: "/apps/finance/billing" },
    { id: "draft", name: "기안서", icon: <FileText /> },
    { id: "approval", name: "지출결의서", icon: <FileCheck2 /> },
    { id: "vehicle-report", name: "차량 운행정산서", icon: <Car />, path: "/admin/driving" },
    { id: "monthly-budget", name: "월간예산", icon: <Wallet /> },
    { id: "revenue-track", name: "계약별 수익 트래킹", icon: <TrendingUp /> },
    { id: "cashflow-cal", name: "현금흐름 캘린더", icon: <CalendarClock /> },
    { id: "finance-settings", name: "금융 연동 설정", icon: <Settings />, path: "/admin/finance-settings" }, // CODEF 설정 페이지 연동
  ],
  hr: [
    { id: "leave-request", name: "휴가신청", icon: <Palmtree />, path: "/leave-request" },
    { id: "leave-mgmt", name: "휴가 관리", icon: <CalendarDays />, path: "/admin/leave" },
    { id: "attendance", name: "출퇴근", icon: <Clock />, path: "/admin/attendance" },
    { id: "org-chart", name: "조직도", icon: <Network />, path: "/admin/org-chart" },
    { id: "labor-contract", name: "근로계약서", icon: <FileSignature /> },
    { id: "comp-leave", name: "보상휴가 관리", icon: <Gift /> },
  ],
  common: [
    { id: "scheduler", name: "통합 스케줄러", icon: <Calendar />, path: "/admin/schedules" },
    { id: "regulations", name: "규정", icon: <BookOpen /> },
    { id: "project-info", name: "프로젝트 정보", icon: <FolderOpen />, path: "/admin/projects" },
    { id: "docs-minutes", name: "문서&회의록", icon: <FileArchive /> },
    { id: "notifications", name: "알림 센터", icon: <Bell /> },
    { id: "global-search", name: "통합 검색", icon: <Search /> },
    { id: "wreath", name: "화환신청", icon: <Flower2 /> },
    { id: "password-mgmt", name: "비밀번호 관리", icon: <KeyRound /> },
  ],
};
