// This file is automatically generated. Do not edit it directly.
// (If you need to customize behavior, do it here in your own repo after export.)
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// 작은 헬퍼: 브라우저 환경인지 체크 (빌드/프리렌더/SSR 대비)
const isBrowser = typeof window !== 'undefined';

// env 누락 시 원인 파악이 어렵기 때문에, 개발 중에는 즉시 터뜨려주는 게 좋음
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // production에서도 조용히 실패하면 디버깅이 더 어려워서 에러를 명확히
  throw new Error(
    [
      'Missing Supabase environment variables.',
      'Please set:',
      '- VITE_SUPABASE_URL',
      '- VITE_SUPABASE_PUBLISHABLE_KEY',
    ].join('\n')
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // 브라우저가 아닐 때(localStorage 없음) 크래시 방지
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
